### PR TITLE
Add max_length parameter for custom config script

### PR DESCRIPTION
**Pull request by purplestove**
- Add `max_length` parameter for config, must be > 0 , default is 32
- Works for String, List and other number value
- Doc

### CODE REVIEW

**Comment by senseiwells** [comment]
Making all rules have `maxLength` is weird, only string rules should have them

**Comment by purplestove** [comment]
Well tbh it was a lot easier to just add the max length thingy to the Rule Objet than to have it for just the List and String. xD
But I can make the change I guess

**Comment by purplestove** [comment]
Made the change. Now the `maxLength` only works for String and List rule.
Also removed the Arucas function `getMaxLength`

**Comment by purplestove** [comment]
Made it nicer like sensei asked, anything else ? xD

**Pull request merged**
