### PR TITLE
Block breaking / InteractBlock / allow Accurateblockplacement at script side

### PR DESCRIPTION
**Pull request by aria1th**

### CODE REVIEW

**Comment by senseiwells** [comment]
Is this ready for merge?

**Comment by aria1th** [comment]
Yes, I only tested this at 1.18.1 server and 1.16.5 singleplayer, but no crashes / problem.
Tested & implemented functions:
**OtherPlayer.getItemForPlayerSlot(slot);
Block.isReplaceable();
Block.rotateYClockwise();
Block.rotateYCounterClockwise();
Block.mirrorFrontBack();
Block.mirrorLeftRight();
Block.isFluid();
Player.fakeLook(yaw, pitch, direction, duration);
Player.updateBreakingBlock(x,y,z);
Player.interactBlock(x,y,z);
Player.attackBlock(x,y,z);
Player.getBlockBreakingSpeed(blockState);
Player.swapPlayerSlotWithHotbar(slot);
World.isAir(x,y,z);**

**Comment by aria1th** [comment]
**World.getEmittedRedstonePower(x,y,z,direction);
Block.sideCoversSmallSquare(direction);
Block.isSideSolidFullSquare(direction);**

**Comment by senseiwells** [comment]
Already merged

**Pull request closed without merging**
